parameters:
    web_studio.form.type.domain_registrar.class:    AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType
    web_studio.form.handler.domain_registrar.class: AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainRegistrarHandler

services:
    #
    # Domain registrar
    #
    web_studio.form.domain_registrar:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - web_studio_domain_registrar_form
            - %web_studio.form.type.domain_registrar.class%

    web_studio.form.type.domain_registrar:
        class: %web_studio.form.type.domain_registrar.class%
        tags:
            - { name: form.type, alias: %web_studio.form.type.domain_registrar.class% }

    web_studio.form.handler.domain_registrar:
        class: %web_studio.form.handler.domain_registrar.class%
        scope: request
        arguments:
            - '@web_studio.form.domain_registrar'
            - '@request'
            - '@doctrine.orm.entity_manager'
