services:
    #
    # Domain registrar
    #
    web_studio.form.domain_registrar:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_domain_registrar_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType

    AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainRegistrarHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainRegistrarHandler
        scope: request
        arguments:
            - '@web_studio.form.domain_registrar'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # Domain mail service
    #
    web_studio.form.domain_mail_service:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_domain_mail_service_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\DomainMailServiceType

    AmaxLab\Oro\WebStudioBundle\Form\Type\DomainMail_serviceType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainMailServiceType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainMailServiceType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainMail_serviceHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainMailServiceHandler
        scope: request
        arguments:
            - '@web_studio.form.domain_mail_service'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # Domain
    #
    web_studio.form.domain:
            class:           Symfony\Component\Form\Form
            factory: [@form.factory, createNamed]
            arguments:
                - web_studio_domain_form
                - AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType

    AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType:
            class: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType
            tags:
                - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainHandler
        scope: request
        arguments:
            - '@web_studio.form.domain'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # Site
    #
    web_studio.form.site:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_site_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType

    AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\SiteHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\SiteHandler
        scope: request
        arguments:
            - '@web_studio.form.site'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # HostProvider
    #
    web_studio.form.host_provider:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_host_provider_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\HostProviderType

    AmaxLab\Oro\WebStudioBundle\Form\Type\HostProviderType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\HostProviderType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\HostProviderType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\HostProviderHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\HostProviderHandler
        scope: request
        arguments:
            - '@web_studio.form.host_provider'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # Host
    #
    web_studio.form.host:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_host_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\HostType

    AmaxLab\Oro\WebStudioBundle\Form\Type\HostType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\HostType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\HostType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\HostHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\HostHandler
        scope: request
        arguments:
            - '@web_studio.form.host'
            - '@request'
            - '@doctrine.orm.entity_manager'
            
    #
    # Project
    #
    web_studio.form.project:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_project_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\ProjectType

    AmaxLab\Oro\WebStudioBundle\Form\Type\ProjectType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\ProjectType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\ProjectHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\ProjectHandler
        scope: request
        arguments:
            - '@web_studio.form.project'
            - '@request'
            - '@doctrine.orm.entity_manager'
            
    #
    # Role
    #
    web_studio.form.role:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_role_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\RoleType

    AmaxLab\Oro\WebStudioBundle\Form\Type\RoleType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\RoleType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\RoleType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\RoleHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\RoleHandler
        scope: request
        arguments:
            - '@web_studio.form.role'
            - '@request'
            - '@doctrine.orm.entity_manager'
