services:
    #
    # Domain registrar
    #
    web_studio.form.domain_registrar:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_domain_registrar_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType

    AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainRegistrarType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainRegistrarHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainRegistrarHandler
        scope: request
        arguments:
            - '@web_studio.form.domain_registrar'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # Domain
    #
    web_studio.form.domain:
            class:           Symfony\Component\Form\Form
            factory: [@form.factory, createNamed]
            arguments:
                - web_studio_domain_form
                - AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType

    AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType:
            class: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType
            tags:
                - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\DomainType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\DomainHandler
        scope: request
        arguments:
            - '@web_studio.form.domain'
            - '@request'
            - '@doctrine.orm.entity_manager'

    #
    # Site
    #
    web_studio.form.site:
        class:           Symfony\Component\Form\Form
        factory: [@form.factory, createNamed]
        arguments:
            - web_studio_site_form
            - AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType

    AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType:
        class: AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: AmaxLab\Oro\WebStudioBundle\Form\Type\SiteType }

    AmaxLab\Oro\WebStudioBundle\Form\Handler\SiteHandler:
        class: AmaxLab\Oro\WebStudioBundle\Form\Handler\SiteHandler
        scope: request
        arguments:
            - '@web_studio.form.site'
            - '@request'
            - '@doctrine.orm.entity_manager'