services:
    AmaxLab\Oro\WebStudioBundle\Repository\CredentialRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\CredentialRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'AmaxLab\Oro\WebStudioBundle\Entity\Credential'

    AmaxLab\Oro\WebStudioBundle\Repository\DomainRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\DomainRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'AmaxLab\Oro\WebStudioBundle\Entity\Domain'

    AmaxLab\Oro\WebStudioBundle\Repository\DomainRegistrarRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\DomainRegistrarRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'AmaxLab\Oro\WebStudioBundle\Entity\Domain'
