parameters:
    web_studio.credential.entity.class: AmaxLab\Oro\WebStudioBundle\Entity\Credential
    web_studio.domain_registrar.entity.class: AmaxLab\Oro\WebStudioBundle\Entity\DomainRegistrar
    web_studio.domain.entity.class: AmaxLab\Oro\WebStudioBundle\Entity\Domain

services:
    AmaxLab\Oro\WebStudioBundle\Repository\CredentialRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\CredentialRepository
        parent: oro_entity.abstract_repository
        arguments:
            - '%web_studio.credential.entity.class%'

    AmaxLab\Oro\WebStudioBundle\Repository\DomainRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\DomainRepository
        parent: oro_entity.abstract_repository
        arguments:
            - '%web_studio.domain.entity.class%'

    AmaxLab\Oro\WebStudioBundle\Repository\DomainRegistrarRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\DomainRegistrarRepository
        parent: oro_entity.abstract_repository
        arguments:
            - '%web_studio.domain_registrar.entity.class%'

    AmaxLab\Oro\WebStudioBundle\Repository\DomainMailServiceRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\DomainMailServiceRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\DomainMailService

    AmaxLab\Oro\WebStudioBundle\Repository\SiteRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\SiteRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\Site

    AmaxLab\Oro\WebStudioBundle\Repository\RoleRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\RoleRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\Role

    AmaxLab\Oro\WebStudioBundle\Repository\HostProviderRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\HostProviderRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\HostProvider

    AmaxLab\Oro\WebStudioBundle\Repository\HostRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\HostRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\Host

    AmaxLab\Oro\WebStudioBundle\Repository\EnvironmentRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\EnvironmentRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\Environment

    AmaxLab\Oro\WebStudioBundle\Repository\ApplicationRepository:
        class: AmaxLab\Oro\WebStudioBundle\Repository\ApplicationRepository
        parent: oro_entity.abstract_repository
        arguments:
            - AmaxLab\Oro\WebStudioBundle\Entity\Application
