datagrids:
    web-studio-domain-registrar-grid:
        acl_resource: true
        extended_entity_name: %web_studio.domain_registrar.entity.class%
        options:
            entityHint: domain registrators
            entity_pagination: true
            mass_actions:
                delete:
                    enabled: false
        source:
            type: orm
            skip_acl_apply: false
            query:
                select:
                    - dr.id
                    - dr.name
                    - dr.createdAt
                    - dr.updatedAt
                    - owner.name as ownerName
                from:
                    - { table: %web_studio.domain_registrar.entity.class%, alias: dr }
                join:
                    left:
                        owner:
                            join: dr.owner
                            alias: owner

        columns:
            name:
                label: amaxlab.oro.webstudio.domainregistrar.name.label
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
            ownerName:
                label: amaxlab.oro.webstudio.domainregistrar.owner.label

        properties:
            id: ~
            update_link:
                type: url
                route: web_studio_domain_registrar_update
                params:
                    - id
            view_link:
                type: url
                route: web_studio_domain_registrar_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye
                acl_resource:  web_studio_domain_registrar_view
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                link:          update_link
                icon:          pencil-square-o
                acl_resource:  web_studio_domain_registrar_update
        sorters:
            columns:
                name:
                    data_name: dr.name
                ownerName:
                    data_name: owner.name
                createdAt:
                    data_name: dr.createdAt
                updatedAt:
                    data_name: dr.updatedAt

            default:
                name: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                name:
                    type: string
                    data_name: dr.name
                createdAt:
                    type: datetime
                    data_name: dr.createdAt
                updatedAt:
                    type: datetime
                    data_name: dr.updatedAt
                businessUnit:
                    label: amaxlab.oro.webstudio.domainregistrar.owner.label
                    type: choice-tree
                    autocomplete_alias: business_units_tree_search_handler
                    data_name: dr.owner
                    className: 'Oro\Bundle\OrganizationBundle\Entity\BusinessUnit'
