navigation:
    menu_config:
        items:
            web_studio_tab:
                label: 'amaxlab.oro.webstudio.navigation.web_studio_tab'
                uri: '#'
            web_studio_host_management:
                label: 'amaxlab.oro.webstudio.navigation.host_management'
                uri: '#'
            web_studio_domain_management:
                label: 'amaxlab.oro.webstudio.navigation.domain_management'
                uri: '#'

            web_studio_host_provider_list:
                label:    'amaxlab.oro.webstudio.hostprovider.entity_plural_label'
                route:    'web_studio_host_provider_index'
                extras:
                    routes: ['web_studio_host_provider_*']
                    description: 'amaxlab.oro.webstudio.hostprovider.entity_description'
            web_studio_host_list:
                label:    'amaxlab.oro.webstudio.host.entity_plural_label'
                route:    'web_studio_host_index'
                extras:
                    routes: ['web_studio_host_*']
                    description: 'amaxlab.oro.webstudio.host.entity_description'

            web_studio_domain_registrar_list:
                label:    'amaxlab.oro.webstudio.domainregistrar.entity_plural_label'
                route:    'web_studio_domain_registrar_index'
                extras:
                    routes: ['web_studio_domain_registrar_*']
                    description: 'amaxlab.oro.webstudio.domainregistrar.entity_description'        
            web_studio_domain_mail_service_list:
                label:    'amaxlab.oro.webstudio.domainmailservice.entity_plural_label'
                route:    'web_studio_domain_mail_service_index'
                extras:
                    routes: ['web_studio_domain_mail_service_*']
                    description: 'amaxlab.oro.webstudio.domainmailservice.entity_description'
            web_studio_domain_dns_service_list:
                label:    'amaxlab.oro.webstudio.domaindnsservice.entity_plural_label'
                route:    'web_studio_domain_dns_service_index'
                extras:
                    routes: ['web_studio_domain_dns_service_*']
                    description: 'amaxlab.oro.webstudio.domaindnsservice.entity_description'
            web_studio_domain_list:
                label:    'amaxlab.oro.webstudio.domain.entity_plural_label'
                route:    'web_studio_domain_index'
                extras:
                    routes: ['web_studio_domain_*']
                    description: 'amaxlab.oro.webstudio.domain.entity_description'
            web_studio_site_list:
                label:    'amaxlab.oro.webstudio.site.entity_plural_label'
                route:    'web_studio_site_index'
                extras:
                    routes: ['web_studio_site_*']
                    description: 'amaxlab.oro.webstudio.site.entity_description'
            web_studio_role_list:
                label:    'amaxlab.oro.webstudio.role.entity_plural_label'
                route:    'web_studio_role_index'
                extras:
                    routes: ['web_studio_role_*']
                    description: 'amaxlab.oro.webstudio.role.entity_description'
            web_studio_project_list:
                label:    'amaxlab.oro.webstudio.project.entity_plural_label'
                route:    'web_studio_project_index'
                extras:
                    routes: ['web_studio_project_*']
                    description: 'amaxlab.oro.webstudio.project.entity_description'

        tree:
            application_menu:
                children:
                    web_studio_tab:
                        children:
                            web_studio_host_management:
                                children:
                                    web_studio_host_provider_list: ~
                                    web_studio_role_list: ~
                                    web_studio_host_list: ~
                            web_studio_domain_management:
                                children:
                                    web_studio_domain_registrar_list: ~
                                    web_studio_domain_mail_service_list: ~
                                    web_studio_domain_dns_service_list: ~
                                    web_studio_domain_list: ~
                            web_studio_site_list: ~
                            web_studio_project_list: ~
    titles:
        web_studio_domain_index:  ~
        web_studio_domain_update: '%domain.name% - Edit'
        web_studio_domain_create: 'Create Domain'
        web_studio_domain_view: '%domain.name%'

        web_studio_domain_registrar_index:  ~
        web_studio_domain_registrar_update: '%domain_registrar.name% - Edit'
        web_studio_domain_registrar_create: 'Create Domain Registrar'
        web_studio_domain_registrar_view: '%domain_registrar.name%'

        web_studio_domain_mail_service_index:  ~
        web_studio_domain_mail_service_update: '%domain_mail_service.name% - Edit'
        web_studio_domain_mail_service_create: 'Create Domain Mail Service'
        web_studio_domain_mail_service_view: '%domain_mail_service.name%'

        web_studio_domain_dns_service_index:  ~
        web_studio_domain_dns_service_update: '%domain_dns_service.name% - Edit'
        web_studio_domain_dns_service_create: 'Create Domain Dns Service'
        web_studio_domain_dns_service_view: '%domain_dns_service.name%'

        web_studio_site_index:  ~
        web_studio_site_update: '%site.name% - Edit'
        web_studio_site_create: 'Create Site'
        web_studio_site_view: '%site.name%'

        web_studio_role_index:  ~
        web_studio_role_update: '%role.name% - Edit'
        web_studio_role_create: 'Create Role'
        web_studio_role_view: '%role.name%'

        web_studio_host_provider_index:  ~
        web_studio_host_provider_update: '%host_provider.name% - Edit'
        web_studio_host_provider_create: 'Create Host Provider'
        web_studio_host_provider_view: '%host_provider.name%'

        web_studio_host_index:  ~
        web_studio_host_update: '%host.name% - Edit'
        web_studio_host_create: 'Create Host'
        web_studio_host_view: '%host.name%'

        web_studio_project_index:  ~
        web_studio_project_update: '%project.name% - Edit'
        web_studio_project_create: 'Create Project'
        web_studio_project_view: '%project.name%'
